
[editor]
true-color = true
cursorline = true
color-modes = true
bufferline = "multiple"
clipboard-provider = "pasteboard"

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "file-name", "spinner"]
center = ["diagnostics"]
right = ["position", "file-encoding", "file-line-ending", "file-type"]

[keys.normal." "]
w = ":w"
q = ":q"
z = ":q!"
" " = ":wq!"
